ListaZaposlenika/Models/ErrorViewModel.cs
namespace ListaZaposlenika.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaZaposlenika/Models/Zaposlenik.cs
using System.ComponentModel.DataAnnotations;

namespace ListaZaposlenika.Models
{
   
    public class Zaposlenik
    {
        [Key]
        public int Id { get; set; }

        public string Ime{ get; set; }

        public string Prezime { get; set; }

        public string Oib { get; set; }

        public DateTime? DatumRođenja { get; set; }
    }
}

ListaZaposlenika/Controllers/HomeController.cs
using ListaZaposlenika.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ListaZaposlenika.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ListaZaposlenika/Controllers/ZaposleniciController.cs
using ListaZaposlenika.Data;
using ListaZaposlenika.Models;
using Microsoft.AspNetCore.Mvc;


namespace ListaZaposlenika.Controllers
{
    public class ZaposleniciController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ZaposleniciController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var listaZaposlenika = _context.Zapposlenici.ToList();
            return View(listaZaposlenika);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Zaposlenik zaposlenik = new Zaposlenik();
            return PartialView("_ZaposlenikModelPartial", zaposlenik);
        }



        [HttpPost]
        public IActionResult Create(Zaposlenik zaposlenici)
        {
            _context.Zapposlenici.Add(zaposlenici);
            _context.SaveChanges();
            return PartialView("_ZaposlenikModelPartial", zaposlenici);
        }



        public IActionResult Details(int id)
        {

            var zaposlenici = _context.Zapposlenici.Where(x => x.Id == id).FirstOrDefault();
            return PartialView("_DetailsZaposlenikModelPartial", zaposlenici);
        }
    }
}

ListaZaposlenika/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ListaZaposlenika/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaZaposlenika</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaZaposlenika.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Zaposlenici" asp-action="Index">ListaZaposlenika</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zaposlenici" asp-action="Index">Home</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ListaZaposlenika - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ListaZaposlenika/Views/Zaposlenici/Index.cshtml
@model IEnumerable<ListaZaposlenika.Models.Zaposlenik>

@{
    ViewData["Title"] = "Index";
}
<div id="PlaceHolderHere"></div>
<button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#dodajZaposlenik"
        data-url="@Url.Action("Create")">
    Create
</button>

<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Oib)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumRođenja)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Oib)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumRođenja)
                </td>

                <td>
                    <button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#dodajZaposlenik"
                        data-url="@Url.Action($"Details/{item.Id}")">
                        Otvori Pop Up
                    </button>
                    

                   


                </td>



            </tr>
        }
    </tbody>
</table>

ListaZaposlenika/Views/Zaposlenici/_DetailsZaposlenikModelPartial.cshtml
@model Zaposlenik

<div class="modal fade" id="dodajZaposlenik">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">

                <h4 class="modal-title" id="dodajZaposlenikLabel">Detalji Zaposlenika</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

                
            </div>


            <div class="modal-body">
                <form>
                    <dl class="btn-group-vertical">

                        
                        <div class="form-group">
                            <dt>@Html.DisplayNameFor(model => model.Ime)</dt>                                                   
                            <label asp-for="Ime">@Model.Ime</label>

                        </div>

                        <div class="form-group">
                            <dt>@Html.DisplayNameFor(model => model.Prezime)</dt>
                            <label asp-for="Prezime">@Model.Prezime</label>

                        </div>

                        <div class="form-group">
                            <dt>@Html.DisplayNameFor(model => model.Oib)</dt>
                            <label asp-for="Oib">@Model.Oib</label>

                        </div>


                        <div class="form-group">
                            <dt>@Html.DisplayNameFor(model => model.DatumRođenja)</dt>
                            <label asp-for="DatumRođenja">@Model.DatumRođenja</label>

                        </div>

                    </dl>
                    

                </form>
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zatvori</button>

        </div>

    </div>

</div>

ListaZaposlenika/Views/Zaposlenici/_ZaposlenikModelPartial.cshtml
@model Zaposlenik

<div class="modal fade" id="dodajZaposlenik">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">

                <h4 class="modal-title" id="dodajZaposlenikLabel">Dodaj Zaposlenika</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>


            <div class="modal-body">
                <form action="Create">

                    <div class="form-group">
                        <label asp-for="Ime"></label>
                        <input asp-for="Ime" class="form-control" />
                        <span asp-validation-for="Ime" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Prezime"></label>
                        <input asp-for="Prezime" class="form-control" />
                        <span asp-validation-for="Prezime" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Oib"></label>
                        <input asp-for="Oib" class="form-control" />
                        <span asp-validation-for="Oib" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="DatumRođenja"></label>
                        <input asp-for="DatumRođenja" class="form-control" />
                        <span asp-validation-for="DatumRođenja" class="text-danger"></span>
                    </div>

                </form>
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
                
            </div>

        </div>

    </div>

</div>